<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Errors;

class ErrorEnvelopeThrowable extends \RuntimeException
{
    public ErrorEnvelope $container;

    public function __construct(string $message, int $statusCode, ErrorEnvelope $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}