<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */


declare(strict_types=1);

namespace Gando\Partner\Hooks;

use Gando\Partner\SDKConfiguration;

interface SDKInitHook
{
    public function sdkInit(SDKConfiguration $config): SDKConfiguration;
}
