<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

use Gando\Partner\Utils\SpeakeasyMetadata;
class AccountsListRequest
{
    /**
     * Filter linked accounts: `active` (default, operable links), `revoked` (disconnected), or `all`.
     *
     * @var ?\Gando\Partner\Models\Operations\AccountsListQueryParamStatus $status
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status')]
    public ?AccountsListQueryParamStatus $status = null;

    /**
     * @param  ?\Gando\Partner\Models\Operations\AccountsListQueryParamStatus  $status
     * @phpstan-pure
     */
    public function __construct(?AccountsListQueryParamStatus $status = null)
    {
        $this->status = $status;
    }
}