<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


/** Filter linked accounts: `active` (default, operable links), `revoked` (disconnected), or `all`. */
enum AccountsListQueryParamStatus: string
{
    case Active = 'active';
    case Revoked = 'revoked';
    case All = 'all';
}
