<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


/** Link status after revocation */
enum AccountsRevokeStatus: string
{
    case Revoked = 'revoked';
}
