<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


/** AccountsRevokeResponseBody - Link revoked */
class AccountsRevokeResponseBody
{
    /**
     *
     * @var \Gando\Partner\Models\Operations\PartnerRevokeAccountResponse $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Gando\Partner\Models\Operations\PartnerRevokeAccountResponse')]
    public PartnerRevokeAccountResponse $data;

    /**
     * Optional human-readable message
     *
     * @var ?string $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $message = null;

    /**
     * Always `true` for successful responses
     *
     * @var bool $success
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('success')]
    public bool $success;

    /**
     * @param  bool  $success
     * @param  \Gando\Partner\Models\Operations\PartnerRevokeAccountResponse  $data
     * @param  ?string  $message
     * @phpstan-pure
     */
    public function __construct(PartnerRevokeAccountResponse $data, ?string $message = null, bool $success = true)
    {
        $this->data = $data;
        $this->message = $message;
        $this->success = $success;
    }
}