<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


/** Void the in-flight deposit payment and set status to `cancelled` (not the same as POST …/cancel which closes an active deposit) */
enum Action: string
{
    case Cancel = 'cancel';
}
