<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class ClientsCreateResponse
{
    /**
     * HTTP response content type for this operation
     *
     * @var string $contentType
     */
    public string $contentType;

    /**
     * HTTP response status code for this operation
     *
     * @var int $statusCode
     */
    public int $statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var \Psr\Http\Message\ResponseInterface $rawResponse
     */
    public \Psr\Http\Message\ResponseInterface $rawResponse;

    /**
     * Client already exists (idempotent create)
     *
     * @var ?\Gando\Partner\Models\Operations\ClientsCreateResponseBody1 $twoHundredApplicationJsonObject
     */
    public ?ClientsCreateResponseBody1 $twoHundredApplicationJsonObject = null;

    /**
     * Client created
     *
     * @var ?\Gando\Partner\Models\Operations\ClientsCreateResponseBody2 $twoHundredAndOneApplicationJsonObject
     */
    public ?ClientsCreateResponseBody2 $twoHundredAndOneApplicationJsonObject = null;

    /**
     * @param  string  $contentType
     * @param  int  $statusCode
     * @param  \Psr\Http\Message\ResponseInterface  $rawResponse
     * @param  ?\Gando\Partner\Models\Operations\ClientsCreateResponseBody1  $twoHundredApplicationJsonObject
     * @param  ?\Gando\Partner\Models\Operations\ClientsCreateResponseBody2  $twoHundredAndOneApplicationJsonObject
     * @phpstan-pure
     */
    public function __construct(string $contentType, int $statusCode, \Psr\Http\Message\ResponseInterface $rawResponse, ?ClientsCreateResponseBody1 $twoHundredApplicationJsonObject = null, ?ClientsCreateResponseBody2 $twoHundredAndOneApplicationJsonObject = null)
    {
        $this->contentType = $contentType;
        $this->statusCode = $statusCode;
        $this->rawResponse = $rawResponse;
        $this->twoHundredApplicationJsonObject = $twoHundredApplicationJsonObject;
        $this->twoHundredAndOneApplicationJsonObject = $twoHundredAndOneApplicationJsonObject;
    }
}