<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;

use Gando\Partner\Utils\SpeakeasyMetadata;
class DepositsSendEmailsRequest
{
    /**
     * Deposit (caution) unique identifier
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var \Gando\Partner\Models\Operations\PartnerDepositEmailsBody $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public PartnerDepositEmailsBody $body;

    /**
     * @param  string  $id
     * @param  \Gando\Partner\Models\Operations\PartnerDepositEmailsBody  $body
     * @phpstan-pure
     */
    public function __construct(string $id, PartnerDepositEmailsBody $body)
    {
        $this->id = $id;
        $this->body = $body;
    }
}