<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


/** Currency code (always EUR) */
enum DepositsListCurrency: string
{
    case Eur = 'EUR';
}
