<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class DepositsCancelPartnerDepositMutationOk
{
    /**
     * Operation completed successfully
     *
     * @var bool $success
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('success')]
    public bool $success;

    /**
     * @param  bool  $success
     * @phpstan-pure
     */
    public function __construct(bool $success = true)
    {
        $this->success = $success;
    }
}