<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


/** DepositsCaptureResponseBody - Capture processed (check `status` for outcome) */
class DepositsCaptureResponseBody
{
    /**
     *
     * @var \Gando\Partner\Models\Operations\PartnerCaptureResult $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Gando\Partner\Models\Operations\PartnerCaptureResult')]
    public PartnerCaptureResult $data;

    /**
     * Optional human-readable message
     *
     * @var ?string $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $message = null;

    /**
     * Always `true` for successful responses
     *
     * @var bool $success
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('success')]
    public bool $success;

    /**
     * @param  bool  $success
     * @param  \Gando\Partner\Models\Operations\PartnerCaptureResult  $data
     * @param  ?string  $message
     * @phpstan-pure
     */
    public function __construct(PartnerCaptureResult $data, ?string $message = null, bool $success = true)
    {
        $this->data = $data;
        $this->message = $message;
        $this->success = $success;
    }
}