<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


/** Event type delivered */
enum EventType: string
{
    case RentalOperatorLinked = 'rental_operator.linked';
    case CautionStatusChanged = 'caution.status_changed';
    case CautionActivated = 'caution.activated';
    case CautionCaptured = 'caution.captured';
    case CautionExpired = 'caution.expired';
    case CautionCancelled = 'caution.cancelled';
}
