<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


/** When `true` or `1`, include per-status counts (requires `account_id`) */
enum IncludeCounts: string
{
    case Zero = '0';
    case One = '1';
    case True = 'true';
    case False = 'false';
}
