<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


/** `Deleted` when removed; `Archived` when soft-deleted instead */
enum Message: string
{
    case Deleted = 'Deleted';
    case Archived = 'Archived';
}
