<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class PartnerDepositListResponse
{
    /**
     * Deposits for the current page
     *
     * @var array<\Gando\Partner\Models\Operations\Item> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Gando\Partner\Models\Operations\Item>')]
    public array $items;

    /**
     * Total deposits matching filters
     *
     * @var int $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    public int $total;

    /**
     * Present only when `include_counts=true` and `account_id` is set
     *
     * @var ?\Gando\Partner\Models\Operations\PartnerDepositListCounts $counts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('counts')]
    #[\Speakeasy\Serializer\Annotation\Type('\Gando\Partner\Models\Operations\PartnerDepositListCounts|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PartnerDepositListCounts $counts = null;

    /**
     * @param  array<\Gando\Partner\Models\Operations\Item>  $items
     * @param  int  $total
     * @param  ?\Gando\Partner\Models\Operations\PartnerDepositListCounts  $counts
     * @phpstan-pure
     */
    public function __construct(array $items, int $total, ?PartnerDepositListCounts $counts = null)
    {
        $this->items = $items;
        $this->total = $total;
        $this->counts = $counts;
    }
}