<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class PartnerCaptureInfo
{
    /**
     * Capture amount in EUR cents
     *
     * @var int $amountCents
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amountCents')]
    public int $amountCents;

    /**
     * Gando collection fee in EUR cents
     *
     * @var int $feeCents
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('feeCents')]
    public int $feeCents;

    /**
     * Net amount credited to the rental operator in EUR cents
     *
     * @var int $netCents
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('netCents')]
    public int $netCents;

    /**
     * Capture status (e.g. paid, pending, failed)
     *
     * @var string $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    public string $status;

    /**
     * Capture reason if provided
     *
     * @var ?string $reason
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reason')]
    public ?string $reason;

    /**
     * @param  int  $amountCents
     * @param  int  $feeCents
     * @param  int  $netCents
     * @param  string  $status
     * @param  ?string  $reason
     * @phpstan-pure
     */
    public function __construct(int $amountCents, int $feeCents, int $netCents, string $status, ?string $reason = null)
    {
        $this->amountCents = $amountCents;
        $this->feeCents = $feeCents;
        $this->netCents = $netCents;
        $this->status = $status;
        $this->reason = $reason;
    }
}