<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class PartnerWebhookRotateSecretResponse
{
    /**
     * New plain signing secret. Store securely; shown once per rotation.
     *
     * @var string $secret
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('secret')]
    public string $secret;

    /**
     * @param  string  $secret
     * @phpstan-pure
     */
    public function __construct(string $secret)
    {
        $this->secret = $secret;
    }
}