<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class PartnerWebhookTestOk
{
    /**
     * HTTP status code returned by your webhook URL
     *
     * @var int $statusCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('statusCode')]
    public int $statusCode;

    /**
     * @param  int  $statusCode
     * @phpstan-pure
     */
    public function __construct(int $statusCode)
    {
        $this->statusCode = $statusCode;
    }
}