<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class PartnerWebhookDeliveryItem
{
    /**
     * Webhook delivery unique identifier
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Event type delivered
     *
     * @var \Gando\Partner\Models\Operations\EventType $eventType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('eventType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Gando\Partner\Models\Operations\EventType')]
    public EventType $eventType;

    /**
     * Delivery attempt number (1-based)
     *
     * @var int $attemptCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attemptCount')]
    public int $attemptCount;

    /**
     * Delivery record creation timestamp (ISO 8601)
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     * HTTP status code returned by your endpoint
     *
     * @var ?int $statusCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('statusCode')]
    public ?int $statusCode;

    /**
     * Error message when delivery failed
     *
     * @var ?string $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    public ?string $error;

    /**
     * ISO 8601 timestamp when delivery succeeded
     *
     * @var ?\DateTime $deliveredAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deliveredAt')]
    public ?\DateTime $deliveredAt;

    /**
     * ISO 8601 timestamp of the next retry, if scheduled
     *
     * @var ?\DateTime $nextRetryAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('nextRetryAt')]
    public ?\DateTime $nextRetryAt;

    /**
     * @param  string  $id
     * @param  \Gando\Partner\Models\Operations\EventType  $eventType
     * @param  int  $attemptCount
     * @param  \DateTime  $createdAt
     * @param  ?int  $statusCode
     * @param  ?string  $error
     * @param  ?\DateTime  $deliveredAt
     * @param  ?\DateTime  $nextRetryAt
     * @phpstan-pure
     */
    public function __construct(string $id, EventType $eventType, int $attemptCount, \DateTime $createdAt, ?int $statusCode = null, ?string $error = null, ?\DateTime $deliveredAt = null, ?\DateTime $nextRetryAt = null)
    {
        $this->id = $id;
        $this->eventType = $eventType;
        $this->attemptCount = $attemptCount;
        $this->createdAt = $createdAt;
        $this->statusCode = $statusCode;
        $this->error = $error;
        $this->deliveredAt = $deliveredAt;
        $this->nextRetryAt = $nextRetryAt;
    }
}