<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class PartnerCreateDepositResponse
{
    /**
     * Deposit unique identifier
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Human-readable deposit reference (e.g. GAN-XXXX)
     *
     * @var string $reference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reference')]
    public string $reference;

    /**
     * Status of the caution: pending (waiting for next step), incomplete (client journey not finished), active (payment authorized), processing (being processed), captured (payment captured), close (caution closed by natural expiration / end of contract), cancelled (caution cancelled manually before activation or while active), payment_issue (payment issue at fee payment), capture_issue (capture/recovery issue)
     *
     * @var \Gando\Partner\Models\Operations\DepositsCreateStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Gando\Partner\Models\Operations\DepositsCreateStatus')]
    public DepositsCreateStatus $status;

    /**
     * Deposit amount in euros
     *
     * @var float $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public float $amount;

    /**
     * Creation timestamp (ISO 8601)
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     * Tenant checkout URL when `inline_redirect` was true on create
     *
     * @var ?string $depositUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deposit_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $depositUrl = null;

    /**
     * @param  string  $id
     * @param  string  $reference
     * @param  \Gando\Partner\Models\Operations\DepositsCreateStatus  $status
     * @param  float  $amount
     * @param  \DateTime  $createdAt
     * @param  ?string  $depositUrl
     * @phpstan-pure
     */
    public function __construct(string $id, string $reference, DepositsCreateStatus $status, float $amount, \DateTime $createdAt, ?string $depositUrl = null)
    {
        $this->id = $id;
        $this->reference = $reference;
        $this->status = $status;
        $this->amount = $amount;
        $this->createdAt = $createdAt;
        $this->depositUrl = $depositUrl;
    }
}