<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class PartnerPatchDepositBody
{
    /**
     * Reassign deposit to another client on the same rental operator account
     *
     * @var ?string $clientId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('client_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $clientId = null;

    /**
     * Void the in-flight deposit payment and set status to `cancelled` (not the same as POST …/cancel which closes an active deposit)
     *
     * @var ?\Gando\Partner\Models\Operations\Action $action
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('action')]
    #[\Speakeasy\Serializer\Annotation\Type('\Gando\Partner\Models\Operations\Action|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Action $action = null;

    /**
     * @param  ?string  $clientId
     * @param  ?\Gando\Partner\Models\Operations\Action  $action
     * @phpstan-pure
     */
    public function __construct(?string $clientId = null, ?Action $action = null)
    {
        $this->clientId = $clientId;
        $this->action = $action;
    }
}