<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class PartnerDeleteWebhookResponse
{
    /**
     * Webhook endpoint was removed
     *
     * @var bool $deleted
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deleted')]
    public bool $deleted;

    /**
     * @param  bool  $deleted
     * @phpstan-pure
     */
    public function __construct(bool $deleted = true)
    {
        $this->deleted = $deleted;
    }
}