<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


class PartnerDepositEmailsBody
{
    /**
     * Recipient email addresses for the deposit completion link
     *
     * @var array<string> $emails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('emails')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $emails;

    /**
     * @param  array<string>  $emails
     * @phpstan-pure
     */
    public function __construct(array $emails)
    {
        $this->emails = $emails;
    }
}