<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


/** PartnerDepositListCounts - Present only when `include_counts=true` and `account_id` is set */
class PartnerDepositListCounts
{
    /**
     * Total deposits for the filtered account
     *
     * @var int $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    public int $total;

    /**
     * Deposit count keyed by status
     *
     * @var array<string, int> $byStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('byStatus')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, int>')]
    public array $byStatus;

    /**
     * @param  int  $total
     * @param  array<string, int>  $byStatus
     * @phpstan-pure
     */
    public function __construct(int $total, array $byStatus)
    {
        $this->total = $total;
        $this->byStatus = $byStatus;
    }
}