<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


/** Sort direction: ascending or descending */
enum SortOrder: string
{
    case Asc = 'asc';
    case Desc = 'desc';
}
