<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


/** Status of the caution: pending (waiting for next step), incomplete (client journey not finished), active (payment authorized), processing (being processed), captured (payment captured), close (caution closed by natural expiration / end of contract), cancelled (caution cancelled manually before activation or while active), payment_issue (payment issue at fee payment), capture_issue (capture/recovery issue) */
enum StatusEur: string
{
    case Pending = 'pending';
    case Incomplete = 'incomplete';
    case Active = 'active';
    case Processing = 'processing';
    case Captured = 'captured';
    case Close = 'close';
    case Cancelled = 'cancelled';
    case PaymentIssue = 'payment_issue';
    case CaptureIssue = 'capture_issue';
}
