<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Operations;


/** WebhooksGetDeliveriesResponseBody - Delivery history */
class WebhooksGetDeliveriesResponseBody
{
    /**
     * Recent webhook delivery attempts for this endpoint
     *
     * @var array<\Gando\Partner\Models\Operations\PartnerWebhookDeliveryItem> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Gando\Partner\Models\Operations\PartnerWebhookDeliveryItem>')]
    public array $data;

    /**
     * Optional human-readable message
     *
     * @var ?string $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $message = null;

    /**
     * Always `true` for successful responses
     *
     * @var bool $success
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('success')]
    public bool $success;

    /**
     * @param  bool  $success
     * @param  array<\Gando\Partner\Models\Operations\PartnerWebhookDeliveryItem>  $data
     * @param  ?string  $message
     * @phpstan-pure
     */
    public function __construct(array $data, ?string $message = null, bool $success = true)
    {
        $this->data = $data;
        $this->message = $message;
        $this->success = $success;
    }
}