<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Components;


/** Machine-readable error code — exhaustive enum in OpenAPI (`PartnerErrorCode`). */
enum Code: string
{
    case InvalidRequest = 'invalid_request';
    case InvalidJsonBody = 'invalid_json_body';
    case MissingApiKey = 'missing_api_key';
    case InvalidApiKey = 'invalid_api_key';
    case ApiKeyRevoked = 'api_key_revoked';
    case AccountNotLinked = 'account_not_linked';
    case AccountRevoked = 'account_revoked';
    case DepositNotFound = 'deposit_not_found';
    case DepositAccessDenied = 'deposit_access_denied';
    case ClientNotFound = 'client_not_found';
    case ClientAccessDenied = 'client_access_denied';
    case WebhookNotFound = 'webhook_not_found';
    case WebhookAccessDenied = 'webhook_access_denied';
    case CaptureNotFound = 'capture_not_found';
    case DepositAlreadyCaptured = 'deposit_already_captured';
    case DepositInvalidStatus = 'deposit_invalid_status';
    case DepositMissingPaymentMethod = 'deposit_missing_payment_method';
    case DepositMissingPaymentIntent = 'deposit_missing_payment_intent';
    case InvalidCaptureAmount = 'invalid_capture_amount';
    case CaptureAmountTooLow = 'capture_amount_too_low';
    case CaptureAmountExceedsDeposit = 'capture_amount_exceeds_deposit';
    case AccountNotCaptureReady = 'account_not_capture_ready';
    case PaymentProcessorUnavailable = 'payment_processor_unavailable';
    case PaymentProcessorError = 'payment_processor_error';
    case InvalidClientId = 'invalid_client_id';
    case ClientNotLinkedToDeposit = 'client_not_linked_to_deposit';
    case ScoringNotFound = 'scoring_not_found';
    case InvalidIdempotencyKey = 'invalid_idempotency_key';
    case IdempotencyKeyConflict = 'idempotency_key_conflict';
    case RedisUnavailable = 'redis_unavailable';
    case RateLimited = 'rate_limited';
    case InternalError = 'internal_error';
    case BadGateway = 'bad_gateway';
    case InvalidParams = 'invalid_params';
    case PartnerNotFound = 'partner_not_found';
    case MissingConnectSecret = 'missing_connect_secret';
    case InvalidSignature = 'invalid_signature';
    case Expired = 'expired';
}
