<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Components;


/** Individual (private) end customer */
enum ParticulierPartnerClientPatchClientType: string
{
    case Particulier = 'particulier';
}
