<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Gando\Partner\Models\Components;

use Gando\Partner\Utils\SpeakeasyMetadata;
class Security
{
    /**
     *
     * @var ?string $partnerApiKeyAuth
     */
    #[SpeakeasyMetadata('security:scheme=true,type=apiKey,subtype=header,name=x-api-key')]
    public ?string $partnerApiKeyAuth = null;

    /**
     *
     * @var ?string $partnerBearerAuth
     */
    #[SpeakeasyMetadata('security:scheme=true,type=http,subtype=bearer,name=Authorization')]
    public ?string $partnerBearerAuth = null;

    /**
     * @param  ?string  $partnerApiKeyAuth
     * @param  ?string  $partnerBearerAuth
     * @phpstan-pure
     */
    public function __construct(?string $partnerApiKeyAuth = null, ?string $partnerBearerAuth = null)
    {
        $this->partnerApiKeyAuth = $partnerApiKeyAuth;
        $this->partnerBearerAuth = $partnerBearerAuth;
    }
}